const cars = [
    {
      id: 1,
      name: "BMW X5",
      price: "$120 / day",
      img: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=60",
      specs: ["Automatic", "2022", "5 Seats", "Diesel"],
    },
    {
      id: 2,
      name: "Audi A4",
      price: "$100 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2021", "5 Seats", "Petrol"],
    },
    {
      id: 3,
      name: "Mercedes C-Class",
      price: "$140 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2023", "5 Seats", "Petrol"],
    },
    {
      id: 4,
      name: "Car Model 4",
      price: "$ 84 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2022", "5 Seats", "Petrol"],
    },
    {
      id: 5,
      name: "Car Model 5",
      price: "$ 85 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2023", "5 Seats", "Petrol"],
    },
    {
      id: 6,
      name: "Car Model 6",
      price: "$ 86 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2021", "5 Seats", "Petrol"],
    },
    {
      id: 7,
      name: "Car Model 7",
      price: "$ 87 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2022", "5 Seats", "Petrol"],
    },
    {
      id: 8,
      name: "Car Model 8",
      price: "$ 88 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2023", "5 Seats", "Petrol"],
    },
    {
      id: 9,
      name: "Car Model 9",
      price: "$ 89 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2021", "5 Seats", "Petrol"],
    },
    {
      id: 10,
      name: "Car Model 10",
      price: "$ 90 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2022", "5 Seats", "Petrol"],
    },
    {
      id: 11,
      name: "Car Model 11",
      price: "$ 91 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2023", "5 Seats", "Petrol"],
    },
    {
      id: 12,
      name: "Car Model 12",
      price: "$ 92 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2021", "5 Seats", "Petrol"],
    },
    {
      id: 13,
      name: "Car Model 13",
      price: "$ 93 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2022", "5 Seats", "Petrol"],
    },
    {
      id: 14,
      name: "Car Model 14",
      price: "$ 94 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2023", "5 Seats", "Petrol"],
    },
    {
      id: 15,
      name: "Car Model 15",
      price: "$ 95 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2021", "5 Seats", "Petrol"],
    },
    {
      id: 16,
      name: "Car Model 16",
      price: "$ 96 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2022", "5 Seats", "Petrol"],
    },
    {
      id: 17,
      name: "Car Model 17",
      price: "$ 97 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2023", "5 Seats", "Petrol"],
    },
    {
      id: 18,
      name: "Car Model 18",
      price: "$ 98 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2021", "5 Seats", "Petrol"],
    },
    {
      id: 19,
      name: "Car Model 19",
      price: "$ 99 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2022", "5 Seats", "Petrol"],
    },
    {
      id: 20,
      name: "Car Model 20",
      price: "$ 100 / day",
      img: "https://via.placeholder.com/250",
      specs: ["Automatic", "2023", "5 Seats", "Petrol"],
    },
  ];
  
  export default cars;
  